// This file is auto-generated

namespace fnwinter.OpenXR
{
    
        enum XrResult
        {
            XR_SUCCESS = 0,
            XR_TIMEOUT_EXPIRED = 1,
            XR_SESSION_LOSS_PENDING = 3,
            XR_EVENT_UNAVAILABLE = 4,
            XR_SPACE_BOUNDS_UNAVAILABLE = 7,
            XR_SESSION_NOT_FOCUSED = 8,
            XR_FRAME_DISCARDED = 9,
            XR_ERROR_VALIDATION_FAILURE = -1,
            XR_ERROR_RUNTIME_FAILURE = -2,
            XR_ERROR_OUT_OF_MEMORY = -3,
            XR_ERROR_API_VERSION_UNSUPPORTED = -4,
            XR_ERROR_INITIALIZATION_FAILED = -6,
            XR_ERROR_FUNCTION_UNSUPPORTED = -7,
            XR_ERROR_FEATURE_UNSUPPORTED = -8,
            XR_ERROR_EXTENSION_NOT_PRESENT = -9,
            XR_ERROR_LIMIT_REACHED = -10,
            XR_ERROR_SIZE_INSUFFICIENT = -11,
            XR_ERROR_HANDLE_INVALID = -12,
            XR_ERROR_INSTANCE_LOST = -13,
            XR_ERROR_SESSION_RUNNING = -14,
            XR_ERROR_SESSION_NOT_RUNNING = -16,
            XR_ERROR_SESSION_LOST = -17,
            XR_ERROR_SYSTEM_INVALID = -18,
            XR_ERROR_PATH_INVALID = -19,
            XR_ERROR_PATH_COUNT_EXCEEDED = -20,
            XR_ERROR_PATH_FORMAT_INVALID = -21,
            XR_ERROR_PATH_UNSUPPORTED = -22,
            XR_ERROR_LAYER_INVALID = -23,
            XR_ERROR_LAYER_LIMIT_EXCEEDED = -24,
            XR_ERROR_SWAPCHAIN_RECT_INVALID = -25,
            XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED = -26,
            XR_ERROR_ACTION_TYPE_MISMATCH = -27,
            XR_ERROR_SESSION_NOT_READY = -28,
            XR_ERROR_SESSION_NOT_STOPPING = -29,
            XR_ERROR_TIME_INVALID = -30,
            XR_ERROR_REFERENCE_SPACE_UNSUPPORTED = -31,
            XR_ERROR_FILE_ACCESS_ERROR = -32,
            XR_ERROR_FILE_CONTENTS_INVALID = -33,
            XR_ERROR_FORM_FACTOR_UNSUPPORTED = -34,
            XR_ERROR_FORM_FACTOR_UNAVAILABLE = -35,
            XR_ERROR_API_LAYER_NOT_PRESENT = -36,
            XR_ERROR_CALL_ORDER_INVALID = -37,
            XR_ERROR_GRAPHICS_DEVICE_INVALID = -38,
            XR_ERROR_POSE_INVALID = -39,
            XR_ERROR_INDEX_OUT_OF_RANGE = -40,
            XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED = -41,
            XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED = -42,
            XR_ERROR_NAME_DUPLICATED = -44,
            XR_ERROR_NAME_INVALID = -45,
            XR_ERROR_ACTIONSET_NOT_ATTACHED = -46,
            XR_ERROR_ACTIONSETS_ALREADY_ATTACHED = -47,
            XR_ERROR_LOCALIZED_NAME_DUPLICATED = -48,
            XR_ERROR_LOCALIZED_NAME_INVALID = -49,
            XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING = -50,
            XR_ERROR_RUNTIME_UNAVAILABLE = -51,
            XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR = -1000003000,
            XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR = -1000003001,
            XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT = -1000039001,
            XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT = -1000053000,
            XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT = -1000055000,
            XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT = -1000066000,
            XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT = -1000097000,
            XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT = -1000097001,
            XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT = -1000097002,
            XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT = -1000097003,
            XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT = -1000097004,
            XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT = -1000097005,
            XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB = -1000101000,
            XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB = -1000108000,
            XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB = -1000113000,
            XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB = -1000113001,
            XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB = -1000113002,
            XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB = -1000113003,
            XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB = -1000118000,
            XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB = -1000118001,
            XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB = -1000118002,
            XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB = -1000118003,
            XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB = -1000118004,
            XR_ERROR_UNKNOWN_PASSTHROUGH_FB = -1000118050,
            XR_ERROR_RENDER_MODEL_KEY_INVALID_FB = -1000119000,
            XR_RENDER_MODEL_UNAVAILABLE_FB = 1000119020,
            XR_ERROR_MARKER_NOT_TRACKED_VARJO = -1000124000,
            XR_ERROR_MARKER_ID_INVALID_VARJO = -1000124001,
            XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT = -1000142001,
            XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT = -1000142002,
            XR_RESULT_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrStructureType
        {
            XR_TYPE_UNKNOWN = 0,
            XR_TYPE_API_LAYER_PROPERTIES = 1,
            XR_TYPE_EXTENSION_PROPERTIES = 2,
            XR_TYPE_INSTANCE_CREATE_INFO = 3,
            XR_TYPE_SYSTEM_GET_INFO = 4,
            XR_TYPE_SYSTEM_PROPERTIES = 5,
            XR_TYPE_VIEW_LOCATE_INFO = 6,
            XR_TYPE_VIEW = 7,
            XR_TYPE_SESSION_CREATE_INFO = 8,
            XR_TYPE_SWAPCHAIN_CREATE_INFO = 9,
            XR_TYPE_SESSION_BEGIN_INFO = 10,
            XR_TYPE_VIEW_STATE = 11,
            XR_TYPE_FRAME_END_INFO = 12,
            XR_TYPE_HAPTIC_VIBRATION = 13,
            XR_TYPE_EVENT_DATA_BUFFER = 16,
            XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING = 17,
            XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED = 18,
            XR_TYPE_ACTION_STATE_BOOLEAN = 23,
            XR_TYPE_ACTION_STATE_FLOAT = 24,
            XR_TYPE_ACTION_STATE_VECTOR2F = 25,
            XR_TYPE_ACTION_STATE_POSE = 27,
            XR_TYPE_ACTION_SET_CREATE_INFO = 28,
            XR_TYPE_ACTION_CREATE_INFO = 29,
            XR_TYPE_INSTANCE_PROPERTIES = 32,
            XR_TYPE_FRAME_WAIT_INFO = 33,
            XR_TYPE_COMPOSITION_LAYER_PROJECTION = 35,
            XR_TYPE_COMPOSITION_LAYER_QUAD = 36,
            XR_TYPE_REFERENCE_SPACE_CREATE_INFO = 37,
            XR_TYPE_ACTION_SPACE_CREATE_INFO = 38,
            XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING = 40,
            XR_TYPE_VIEW_CONFIGURATION_VIEW = 41,
            XR_TYPE_SPACE_LOCATION = 42,
            XR_TYPE_SPACE_VELOCITY = 43,
            XR_TYPE_FRAME_STATE = 44,
            XR_TYPE_VIEW_CONFIGURATION_PROPERTIES = 45,
            XR_TYPE_FRAME_BEGIN_INFO = 46,
            XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW = 48,
            XR_TYPE_EVENT_DATA_EVENTS_LOST = 49,
            XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING = 51,
            XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED = 52,
            XR_TYPE_INTERACTION_PROFILE_STATE = 53,
            XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO = 55,
            XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO = 56,
            XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO = 57,
            XR_TYPE_ACTION_STATE_GET_INFO = 58,
            XR_TYPE_HAPTIC_ACTION_INFO = 59,
            XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO = 60,
            XR_TYPE_ACTIONS_SYNC_INFO = 61,
            XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO = 62,
            XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO = 63,
            XR_TYPE_COMPOSITION_LAYER_CUBE_KHR = 1000006000,
            XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR = 1000008000,
            XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR = 1000010000,
            XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR = 1000014000,
            XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT = 1000015000,
            XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR = 1000017000,
            XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR = 1000018000,
            XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT = 1000019000,
            XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT = 1000019001,
            XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT = 1000019002,
            XR_TYPE_DEBUG_UTILS_LABEL_EXT = 1000019003,
            XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR = 1000023000,
            XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR = 1000023001,
            XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR = 1000023002,
            XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR = 1000023003,
            XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR = 1000023004,
            XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR = 1000023005,
            XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR = 1000024001,
            XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR = 1000024002,
            XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR = 1000024003,
            XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR = 1000025000,
            XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR = 1000025001,
            XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR = 1000025002,
            XR_TYPE_GRAPHICS_BINDING_D3D11_KHR = 1000027000,
            XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR = 1000027001,
            XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR = 1000027002,
            XR_TYPE_GRAPHICS_BINDING_D3D12_KHR = 1000028000,
            XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR = 1000028001,
            XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR = 1000028002,
            XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT = 1000030000,
            XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT = 1000030001,
            XR_TYPE_VISIBILITY_MASK_KHR = 1000031000,
            XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR = 1000031001,
            XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX = 1000033000,
            XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX = 1000033003,
            XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR = 1000034000,
            XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT = 1000039000,
            XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT = 1000039001,
            XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB = 1000040000,
            XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB = 1000041001,
            XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT = 1000046000,
            XR_TYPE_GRAPHICS_BINDING_EGL_MNDX = 1000048004,
            XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT = 1000049000,
            XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT = 1000049001,
            XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT = 1000049002,
            XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT = 1000049003,
            XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT = 1000051000,
            XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT = 1000051001,
            XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT = 1000051002,
            XR_TYPE_HAND_JOINT_LOCATIONS_EXT = 1000051003,
            XR_TYPE_HAND_JOINT_VELOCITIES_EXT = 1000051004,
            XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT = 1000052000,
            XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT = 1000052001,
            XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT = 1000052002,
            XR_TYPE_HAND_MESH_MSFT = 1000052003,
            XR_TYPE_HAND_POSE_TYPE_INFO_MSFT = 1000052004,
            XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT = 1000053000,
            XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT = 1000053001,
            XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT = 1000053002,
            XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT = 1000053003,
            XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT = 1000053004,
            XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT = 1000053005,
            XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT = 1000055000,
            XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT = 1000055001,
            XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT = 1000055002,
            XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT = 1000055003,
            XR_TYPE_CONTROLLER_MODEL_STATE_MSFT = 1000055004,
            XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC = 1000059000,
            XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT = 1000063000,
            XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT = 1000066000,
            XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT = 1000066001,
            XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB = 1000070000,
            XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB = 1000072000,
            XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT = 1000078000,
            XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE = 1000079000,
            XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT = 1000080000,
            XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR = 1000089000,
            XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR = 1000090000,
            XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR = 1000090001,
            XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR = 1000090003,
            XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR = 1000091000,
            XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT = 1000097000,
            XR_TYPE_SCENE_CREATE_INFO_MSFT = 1000097001,
            XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT = 1000097002,
            XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT = 1000097003,
            XR_TYPE_SCENE_COMPONENTS_MSFT = 1000097004,
            XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT = 1000097005,
            XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT = 1000097006,
            XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT = 1000097007,
            XR_TYPE_SCENE_OBJECTS_MSFT = 1000097008,
            XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT = 1000097009,
            XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT = 1000097010,
            XR_TYPE_SCENE_PLANES_MSFT = 1000097011,
            XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT = 1000097012,
            XR_TYPE_SCENE_MESHES_MSFT = 1000097013,
            XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT = 1000097014,
            XR_TYPE_SCENE_MESH_BUFFERS_MSFT = 1000097015,
            XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT = 1000097016,
            XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT = 1000097017,
            XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT = 1000097018,
            XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT = 1000098000,
            XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT = 1000098001,
            XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB = 1000101000,
            XR_TYPE_VIVE_TRACKER_PATHS_HTCX = 1000103000,
            XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX = 1000103001,
            XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC = 1000104000,
            XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC = 1000104001,
            XR_TYPE_FACIAL_EXPRESSIONS_HTC = 1000104002,
            XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB = 1000108000,
            XR_TYPE_HAND_TRACKING_MESH_FB = 1000110001,
            XR_TYPE_HAND_TRACKING_SCALE_FB = 1000110003,
            XR_TYPE_HAND_TRACKING_AIM_STATE_FB = 1000111001,
            XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB = 1000112000,
            XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB = 1000113004,
            XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB = 1000113003,
            XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB = 1000113007,
            XR_TYPE_SPACE_COMPONENT_STATUS_FB = 1000113001,
            XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB = 1000113005,
            XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB = 1000113006,
            XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB = 1000114000,
            XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB = 1000114001,
            XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB = 1000114002,
            XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB = 1000115000,
            XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB = 1000116009,
            XR_TYPE_KEYBOARD_TRACKING_QUERY_FB = 1000116004,
            XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB = 1000116002,
            XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB = 1000117001,
            XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB = 1000118000,
            XR_TYPE_PASSTHROUGH_CREATE_INFO_FB = 1000118001,
            XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB = 1000118002,
            XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB = 1000118003,
            XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB = 1000118004,
            XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB = 1000118005,
            XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB = 1000118006,
            XR_TYPE_PASSTHROUGH_STYLE_FB = 1000118020,
            XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB = 1000118021,
            XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB = 1000118022,
            XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB = 1000118023,
            XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB = 1000118030,
            XR_TYPE_RENDER_MODEL_PATH_INFO_FB = 1000119000,
            XR_TYPE_RENDER_MODEL_PROPERTIES_FB = 1000119001,
            XR_TYPE_RENDER_MODEL_BUFFER_FB = 1000119002,
            XR_TYPE_RENDER_MODEL_LOAD_INFO_FB = 1000119003,
            XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB = 1000119004,
            XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB = 1000119005,
            XR_TYPE_BINDING_MODIFICATIONS_KHR = 1000120000,
            XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO = 1000121000,
            XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO = 1000121001,
            XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO = 1000121002,
            XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO = 1000122000,
            XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO = 1000124000,
            XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO = 1000124001,
            XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO = 1000124002,
            XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT = 1000142000,
            XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT = 1000142001,
            XR_TYPE_SPACE_QUERY_INFO_FB = 1000156001,
            XR_TYPE_SPACE_QUERY_RESULTS_FB = 1000156002,
            XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB = 1000156003,
            XR_TYPE_SPACE_UUID_FILTER_INFO_FB = 1000156054,
            XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB = 1000156052,
            XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB = 1000156103,
            XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB = 1000156104,
            XR_TYPE_SPACE_SAVE_INFO_FB = 1000158000,
            XR_TYPE_SPACE_ERASE_INFO_FB = 1000158001,
            XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB = 1000158106,
            XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB = 1000158107,
            XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB = 1000160000,
            XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB = 1000161000,
            XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB = 1000162000,
            XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB = 1000163000,
            XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB = 1000171000,
            XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB = 1000171001,
            XR_TYPE_SEMANTIC_LABELS_FB = 1000175000,
            XR_TYPE_ROOM_LAYOUT_FB = 1000175001,
            XR_TYPE_BOUNDARY_2D_FB = 1000175002,
            XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE = 1000196000,
            XR_TYPE_SPACE_CONTAINER_FB = 1000199000,
            XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB = 1000203002,
            XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB = 1000204000,
            XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META = 1000227000,
            XR_TYPE_PERFORMANCE_METRICS_STATE_META = 1000232001,
            XR_TYPE_PERFORMANCE_METRICS_COUNTER_META = 1000232002,
            XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META = 1000245000,
            XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC = 1000317001,
            XR_TYPE_PASSTHROUGH_COLOR_HTC = 1000317002,
            XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC = 1000317003,
            XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC = 1000317004,
            XR_TYPE_FOVEATION_APPLY_INFO_HTC = 1000318000,
            XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC = 1000318001,
            XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC = 1000318002,
            XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT = 1000373000,
            XR_TYPE_GRAPHICS_BINDING_VULKAN2_KHR = XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR,
            XR_TYPE_SWAPCHAIN_IMAGE_VULKAN2_KHR = XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR,
            XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN2_KHR = XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR,
            XR_STRUCTURE_TYPE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrFormFactor
        {
            XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY = 1,
            XR_FORM_FACTOR_HANDHELD_DISPLAY = 2,
            XR_FORM_FACTOR_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrViewConfigurationType
        {
            XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO = 1,
            XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO = 2,
            XR_VIEW_CONFIGURATION_TYPE_PRIMARY_QUAD_VARJO = 1000037000,
            XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT = 1000054000,
            XR_VIEW_CONFIGURATION_TYPE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrEnvironmentBlendMode
        {
            XR_ENVIRONMENT_BLEND_MODE_OPAQUE = 1,
            XR_ENVIRONMENT_BLEND_MODE_ADDITIVE = 2,
            XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND = 3,
            XR_ENVIRONMENT_BLEND_MODE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrReferenceSpaceType
        {
            XR_REFERENCE_SPACE_TYPE_VIEW = 1,
            XR_REFERENCE_SPACE_TYPE_LOCAL = 2,
            XR_REFERENCE_SPACE_TYPE_STAGE = 3,
            XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT = 1000038000,
            XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO = 1000121000,
            XR_REFERENCE_SPACE_TYPE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrActionType
        {
            XR_ACTION_TYPE_BOOLEAN_INPUT = 1,
            XR_ACTION_TYPE_FLOAT_INPUT = 2,
            XR_ACTION_TYPE_VECTOR2F_INPUT = 3,
            XR_ACTION_TYPE_POSE_INPUT = 4,
            XR_ACTION_TYPE_VIBRATION_OUTPUT = 100,
            XR_ACTION_TYPE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrEyeVisibility
        {
            XR_EYE_VISIBILITY_BOTH = 0,
            XR_EYE_VISIBILITY_LEFT = 1,
            XR_EYE_VISIBILITY_RIGHT = 2,
            XR_EYE_VISIBILITY_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrSessionState
        {
            XR_SESSION_STATE_UNKNOWN = 0,
            XR_SESSION_STATE_IDLE = 1,
            XR_SESSION_STATE_READY = 2,
            XR_SESSION_STATE_SYNCHRONIZED = 3,
            XR_SESSION_STATE_VISIBLE = 4,
            XR_SESSION_STATE_FOCUSED = 5,
            XR_SESSION_STATE_STOPPING = 6,
            XR_SESSION_STATE_LOSS_PENDING = 7,
            XR_SESSION_STATE_EXITING = 8,
            XR_SESSION_STATE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrObjectType
        {
            XR_OBJECT_TYPE_UNKNOWN = 0,
            XR_OBJECT_TYPE_INSTANCE = 1,
            XR_OBJECT_TYPE_SESSION = 2,
            XR_OBJECT_TYPE_SWAPCHAIN = 3,
            XR_OBJECT_TYPE_SPACE = 4,
            XR_OBJECT_TYPE_ACTION_SET = 5,
            XR_OBJECT_TYPE_ACTION = 6,
            XR_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT = 1000019000,
            XR_OBJECT_TYPE_SPATIAL_ANCHOR_MSFT = 1000039000,
            XR_OBJECT_TYPE_SPATIAL_GRAPH_NODE_BINDING_MSFT = 1000049000,
            XR_OBJECT_TYPE_HAND_TRACKER_EXT = 1000051000,
            XR_OBJECT_TYPE_SCENE_OBSERVER_MSFT = 1000097000,
            XR_OBJECT_TYPE_SCENE_MSFT = 1000097001,
            XR_OBJECT_TYPE_FACIAL_TRACKER_HTC = 1000104000,
            XR_OBJECT_TYPE_FOVEATION_PROFILE_FB = 1000114000,
            XR_OBJECT_TYPE_TRIANGLE_MESH_FB = 1000117000,
            XR_OBJECT_TYPE_PASSTHROUGH_FB = 1000118000,
            XR_OBJECT_TYPE_PASSTHROUGH_LAYER_FB = 1000118002,
            XR_OBJECT_TYPE_GEOMETRY_INSTANCE_FB = 1000118004,
            XR_OBJECT_TYPE_SPATIAL_ANCHOR_STORE_CONNECTION_MSFT = 1000142000,
            XR_OBJECT_TYPE_PASSTHROUGH_HTC = 1000317000,
            XR_OBJECT_TYPE_MAX_ENUM = 0x7FFFFFFF,
            
        }
    
        enum XrVisibilityMaskTypeKHR
        {
            XR_VISIBILITY_MASK_TYPE_HIDDEN_TRIANGLE_MESH_KHR = 1,
            XR_VISIBILITY_MASK_TYPE_VISIBLE_TRIANGLE_MESH_KHR = 2,
            XR_VISIBILITY_MASK_TYPE_LINE_LOOP_KHR = 3,
            XR_VISIBILITY_MASK_TYPE_MAX_ENUM_KHR = 0x7FFFFFFF,
            
        }
    
        enum XrPerfSettingsDomainEXT
        {
            XR_PERF_SETTINGS_DOMAIN_CPU_EXT = 1,
            XR_PERF_SETTINGS_DOMAIN_GPU_EXT = 2,
            XR_PERF_SETTINGS_DOMAIN_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrPerfSettingsSubDomainEXT
        {
            XR_PERF_SETTINGS_SUB_DOMAIN_COMPOSITING_EXT = 1,
            XR_PERF_SETTINGS_SUB_DOMAIN_RENDERING_EXT = 2,
            XR_PERF_SETTINGS_SUB_DOMAIN_THERMAL_EXT = 3,
            XR_PERF_SETTINGS_SUB_DOMAIN_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrPerfSettingsLevelEXT
        {
            XR_PERF_SETTINGS_LEVEL_POWER_SAVINGS_EXT = 0,
            XR_PERF_SETTINGS_LEVEL_SUSTAINED_LOW_EXT = 25,
            XR_PERF_SETTINGS_LEVEL_SUSTAINED_HIGH_EXT = 50,
            XR_PERF_SETTINGS_LEVEL_BOOST_EXT = 75,
            XR_PERF_SETTINGS_LEVEL_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrPerfSettingsNotificationLevelEXT
        {
            XR_PERF_SETTINGS_NOTIF_LEVEL_NORMAL_EXT = 0,
            XR_PERF_SETTINGS_NOTIF_LEVEL_WARNING_EXT = 25,
            XR_PERF_SETTINGS_NOTIF_LEVEL_IMPAIRED_EXT = 75,
            XR_PERF_SETTINGS_NOTIFICATION_LEVEL_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrBlendFactorFB
        {
            XR_BLEND_FACTOR_ZERO_FB = 0,
            XR_BLEND_FACTOR_ONE_FB = 1,
            XR_BLEND_FACTOR_SRC_ALPHA_FB = 2,
            XR_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA_FB = 3,
            XR_BLEND_FACTOR_DST_ALPHA_FB = 4,
            XR_BLEND_FACTOR_ONE_MINUS_DST_ALPHA_FB = 5,
            XR_BLEND_FACTOR_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrSpatialGraphNodeTypeMSFT
        {
            XR_SPATIAL_GRAPH_NODE_TYPE_STATIC_MSFT = 1,
            XR_SPATIAL_GRAPH_NODE_TYPE_DYNAMIC_MSFT = 2,
            XR_SPATIAL_GRAPH_NODE_TYPE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrHandEXT
        {
            XR_HAND_LEFT_EXT = 1,
            XR_HAND_RIGHT_EXT = 2,
            XR_HAND_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrHandJointEXT
        {
            XR_HAND_JOINT_PALM_EXT = 0,
            XR_HAND_JOINT_WRIST_EXT = 1,
            XR_HAND_JOINT_THUMB_METACARPAL_EXT = 2,
            XR_HAND_JOINT_THUMB_PROXIMAL_EXT = 3,
            XR_HAND_JOINT_THUMB_DISTAL_EXT = 4,
            XR_HAND_JOINT_THUMB_TIP_EXT = 5,
            XR_HAND_JOINT_INDEX_METACARPAL_EXT = 6,
            XR_HAND_JOINT_INDEX_PROXIMAL_EXT = 7,
            XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT = 8,
            XR_HAND_JOINT_INDEX_DISTAL_EXT = 9,
            XR_HAND_JOINT_INDEX_TIP_EXT = 10,
            XR_HAND_JOINT_MIDDLE_METACARPAL_EXT = 11,
            XR_HAND_JOINT_MIDDLE_PROXIMAL_EXT = 12,
            XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT = 13,
            XR_HAND_JOINT_MIDDLE_DISTAL_EXT = 14,
            XR_HAND_JOINT_MIDDLE_TIP_EXT = 15,
            XR_HAND_JOINT_RING_METACARPAL_EXT = 16,
            XR_HAND_JOINT_RING_PROXIMAL_EXT = 17,
            XR_HAND_JOINT_RING_INTERMEDIATE_EXT = 18,
            XR_HAND_JOINT_RING_DISTAL_EXT = 19,
            XR_HAND_JOINT_RING_TIP_EXT = 20,
            XR_HAND_JOINT_LITTLE_METACARPAL_EXT = 21,
            XR_HAND_JOINT_LITTLE_PROXIMAL_EXT = 22,
            XR_HAND_JOINT_LITTLE_INTERMEDIATE_EXT = 23,
            XR_HAND_JOINT_LITTLE_DISTAL_EXT = 24,
            XR_HAND_JOINT_LITTLE_TIP_EXT = 25,
            XR_HAND_JOINT_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrHandJointSetEXT
        {
            XR_HAND_JOINT_SET_DEFAULT_EXT = 0,
            XR_HAND_JOINT_SET_HAND_WITH_FOREARM_ULTRALEAP = 1000149000,
            XR_HAND_JOINT_SET_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrHandPoseTypeMSFT
        {
            XR_HAND_POSE_TYPE_TRACKED_MSFT = 0,
            XR_HAND_POSE_TYPE_REFERENCE_OPEN_PALM_MSFT = 1,
            XR_HAND_POSE_TYPE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrReprojectionModeMSFT
        {
            XR_REPROJECTION_MODE_DEPTH_MSFT = 1,
            XR_REPROJECTION_MODE_PLANAR_FROM_DEPTH_MSFT = 2,
            XR_REPROJECTION_MODE_PLANAR_MANUAL_MSFT = 3,
            XR_REPROJECTION_MODE_ORIENTATION_ONLY_MSFT = 4,
            XR_REPROJECTION_MODE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrHandJointsMotionRangeEXT
        {
            XR_HAND_JOINTS_MOTION_RANGE_UNOBSTRUCTED_EXT = 1,
            XR_HAND_JOINTS_MOTION_RANGE_CONFORMING_TO_CONTROLLER_EXT = 2,
            XR_HAND_JOINTS_MOTION_RANGE_MAX_ENUM_EXT = 0x7FFFFFFF,
            
        }
    
        enum XrSceneComputeFeatureMSFT
        {
            XR_SCENE_COMPUTE_FEATURE_PLANE_MSFT = 1,
            XR_SCENE_COMPUTE_FEATURE_PLANE_MESH_MSFT = 2,
            XR_SCENE_COMPUTE_FEATURE_VISUAL_MESH_MSFT = 3,
            XR_SCENE_COMPUTE_FEATURE_COLLIDER_MESH_MSFT = 4,
            XR_SCENE_COMPUTE_FEATURE_SERIALIZE_SCENE_MSFT = 1000098000,
            XR_SCENE_COMPUTE_FEATURE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrSceneComputeConsistencyMSFT
        {
            XR_SCENE_COMPUTE_CONSISTENCY_SNAPSHOT_COMPLETE_MSFT = 1,
            XR_SCENE_COMPUTE_CONSISTENCY_SNAPSHOT_INCOMPLETE_FAST_MSFT = 2,
            XR_SCENE_COMPUTE_CONSISTENCY_OCCLUSION_OPTIMIZED_MSFT = 3,
            XR_SCENE_COMPUTE_CONSISTENCY_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrMeshComputeLodMSFT
        {
            XR_MESH_COMPUTE_LOD_COARSE_MSFT = 1,
            XR_MESH_COMPUTE_LOD_MEDIUM_MSFT = 2,
            XR_MESH_COMPUTE_LOD_FINE_MSFT = 3,
            XR_MESH_COMPUTE_LOD_UNLIMITED_MSFT = 4,
            XR_MESH_COMPUTE_LOD_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrSceneComponentTypeMSFT
        {
            XR_SCENE_COMPONENT_TYPE_INVALID_MSFT = -1,
            XR_SCENE_COMPONENT_TYPE_OBJECT_MSFT = 1,
            XR_SCENE_COMPONENT_TYPE_PLANE_MSFT = 2,
            XR_SCENE_COMPONENT_TYPE_VISUAL_MESH_MSFT = 3,
            XR_SCENE_COMPONENT_TYPE_COLLIDER_MESH_MSFT = 4,
            XR_SCENE_COMPONENT_TYPE_SERIALIZED_SCENE_FRAGMENT_MSFT = 1000098000,
            XR_SCENE_COMPONENT_TYPE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrSceneObjectTypeMSFT
        {
            XR_SCENE_OBJECT_TYPE_UNCATEGORIZED_MSFT = -1,
            XR_SCENE_OBJECT_TYPE_BACKGROUND_MSFT = 1,
            XR_SCENE_OBJECT_TYPE_WALL_MSFT = 2,
            XR_SCENE_OBJECT_TYPE_FLOOR_MSFT = 3,
            XR_SCENE_OBJECT_TYPE_CEILING_MSFT = 4,
            XR_SCENE_OBJECT_TYPE_PLATFORM_MSFT = 5,
            XR_SCENE_OBJECT_TYPE_INFERRED_MSFT = 6,
            XR_SCENE_OBJECT_TYPE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrScenePlaneAlignmentTypeMSFT
        {
            XR_SCENE_PLANE_ALIGNMENT_TYPE_NON_ORTHOGONAL_MSFT = 0,
            XR_SCENE_PLANE_ALIGNMENT_TYPE_HORIZONTAL_MSFT = 1,
            XR_SCENE_PLANE_ALIGNMENT_TYPE_VERTICAL_MSFT = 2,
            XR_SCENE_PLANE_ALIGNMENT_TYPE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrSceneComputeStateMSFT
        {
            XR_SCENE_COMPUTE_STATE_NONE_MSFT = 0,
            XR_SCENE_COMPUTE_STATE_UPDATING_MSFT = 1,
            XR_SCENE_COMPUTE_STATE_COMPLETED_MSFT = 2,
            XR_SCENE_COMPUTE_STATE_COMPLETED_WITH_ERROR_MSFT = 3,
            XR_SCENE_COMPUTE_STATE_MAX_ENUM_MSFT = 0x7FFFFFFF,
            
        }
    
        enum XrEyeExpressionHTC
        {
            XR_EYE_EXPRESSION_LEFT_BLINK_HTC = 0,
            XR_EYE_EXPRESSION_LEFT_WIDE_HTC = 1,
            XR_EYE_EXPRESSION_RIGHT_BLINK_HTC = 2,
            XR_EYE_EXPRESSION_RIGHT_WIDE_HTC = 3,
            XR_EYE_EXPRESSION_LEFT_SQUEEZE_HTC = 4,
            XR_EYE_EXPRESSION_RIGHT_SQUEEZE_HTC = 5,
            XR_EYE_EXPRESSION_LEFT_DOWN_HTC = 6,
            XR_EYE_EXPRESSION_RIGHT_DOWN_HTC = 7,
            XR_EYE_EXPRESSION_LEFT_OUT_HTC = 8,
            XR_EYE_EXPRESSION_RIGHT_IN_HTC = 9,
            XR_EYE_EXPRESSION_LEFT_IN_HTC = 10,
            XR_EYE_EXPRESSION_RIGHT_OUT_HTC = 11,
            XR_EYE_EXPRESSION_LEFT_UP_HTC = 12,
            XR_EYE_EXPRESSION_RIGHT_UP_HTC = 13,
            XR_EYE_EXPRESSION_MAX_ENUM_HTC = 0x7FFFFFFF,
            
        }
    
        enum XrLipExpressionHTC
        {
            XR_LIP_EXPRESSION_JAW_RIGHT_HTC = 0,
            XR_LIP_EXPRESSION_JAW_LEFT_HTC = 1,
            XR_LIP_EXPRESSION_JAW_FORWARD_HTC = 2,
            XR_LIP_EXPRESSION_JAW_OPEN_HTC = 3,
            XR_LIP_EXPRESSION_MOUTH_APE_SHAPE_HTC = 4,
            XR_LIP_EXPRESSION_MOUTH_UPPER_RIGHT_HTC = 5,
            XR_LIP_EXPRESSION_MOUTH_UPPER_LEFT_HTC = 6,
            XR_LIP_EXPRESSION_MOUTH_LOWER_RIGHT_HTC = 7,
            XR_LIP_EXPRESSION_MOUTH_LOWER_LEFT_HTC = 8,
            XR_LIP_EXPRESSION_MOUTH_UPPER_OVERTURN_HTC = 9,
            XR_LIP_EXPRESSION_MOUTH_LOWER_OVERTURN_HTC = 10,
            XR_LIP_EXPRESSION_MOUTH_POUT_HTC = 11,
            XR_LIP_EXPRESSION_MOUTH_SMILE_RIGHT_HTC = 12,
            XR_LIP_EXPRESSION_MOUTH_SMILE_LEFT_HTC = 13,
            XR_LIP_EXPRESSION_MOUTH_SAD_RIGHT_HTC = 14,
            XR_LIP_EXPRESSION_MOUTH_SAD_LEFT_HTC = 15,
            XR_LIP_EXPRESSION_CHEEK_PUFF_RIGHT_HTC = 16,
            XR_LIP_EXPRESSION_CHEEK_PUFF_LEFT_HTC = 17,
            XR_LIP_EXPRESSION_CHEEK_SUCK_HTC = 18,
            XR_LIP_EXPRESSION_MOUTH_UPPER_UPRIGHT_HTC = 19,
            XR_LIP_EXPRESSION_MOUTH_UPPER_UPLEFT_HTC = 20,
            XR_LIP_EXPRESSION_MOUTH_LOWER_DOWNRIGHT_HTC = 21,
            XR_LIP_EXPRESSION_MOUTH_LOWER_DOWNLEFT_HTC = 22,
            XR_LIP_EXPRESSION_MOUTH_UPPER_INSIDE_HTC = 23,
            XR_LIP_EXPRESSION_MOUTH_LOWER_INSIDE_HTC = 24,
            XR_LIP_EXPRESSION_MOUTH_LOWER_OVERLAY_HTC = 25,
            XR_LIP_EXPRESSION_TONGUE_LONGSTEP1_HTC = 26,
            XR_LIP_EXPRESSION_TONGUE_LEFT_HTC = 27,
            XR_LIP_EXPRESSION_TONGUE_RIGHT_HTC = 28,
            XR_LIP_EXPRESSION_TONGUE_UP_HTC = 29,
            XR_LIP_EXPRESSION_TONGUE_DOWN_HTC = 30,
            XR_LIP_EXPRESSION_TONGUE_ROLL_HTC = 31,
            XR_LIP_EXPRESSION_TONGUE_LONGSTEP2_HTC = 32,
            XR_LIP_EXPRESSION_TONGUE_UPRIGHT_MORPH_HTC = 33,
            XR_LIP_EXPRESSION_TONGUE_UPLEFT_MORPH_HTC = 34,
            XR_LIP_EXPRESSION_TONGUE_DOWNRIGHT_MORPH_HTC = 35,
            XR_LIP_EXPRESSION_TONGUE_DOWNLEFT_MORPH_HTC = 36,
            XR_LIP_EXPRESSION_MAX_ENUM_HTC = 0x7FFFFFFF,
            
        }
    
        enum XrFacialTrackingTypeHTC
        {
            XR_FACIAL_TRACKING_TYPE_EYE_DEFAULT_HTC = 1,
            XR_FACIAL_TRACKING_TYPE_LIP_DEFAULT_HTC = 2,
            XR_FACIAL_TRACKING_TYPE_MAX_ENUM_HTC = 0x7FFFFFFF,
            
        }
    
        enum XrColorSpaceFB
        {
            XR_COLOR_SPACE_UNMANAGED_FB = 0,
            XR_COLOR_SPACE_REC2020_FB = 1,
            XR_COLOR_SPACE_REC709_FB = 2,
            XR_COLOR_SPACE_RIFT_CV1_FB = 3,
            XR_COLOR_SPACE_RIFT_S_FB = 4,
            XR_COLOR_SPACE_QUEST_FB = 5,
            XR_COLOR_SPACE_P3_FB = 6,
            XR_COLOR_SPACE_ADOBE_RGB_FB = 7,
            XR_COLOR_SPACE_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrSpaceComponentTypeFB
        {
            XR_SPACE_COMPONENT_TYPE_LOCATABLE_FB = 0,
            XR_SPACE_COMPONENT_TYPE_STORABLE_FB = 1,
            XR_SPACE_COMPONENT_TYPE_BOUNDED_2D_FB = 3,
            XR_SPACE_COMPONENT_TYPE_BOUNDED_3D_FB = 4,
            XR_SPACE_COMPONENT_TYPE_SEMANTIC_LABELS_FB = 5,
            XR_SPACE_COMPONENT_TYPE_ROOM_LAYOUT_FB = 6,
            XR_SPACE_COMPONENT_TYPE_SPACE_CONTAINER_FB = 7,
            XR_SPACE_COMPONENT_TYPE_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrFoveationLevelFB
        {
            XR_FOVEATION_LEVEL_NONE_FB = 0,
            XR_FOVEATION_LEVEL_LOW_FB = 1,
            XR_FOVEATION_LEVEL_MEDIUM_FB = 2,
            XR_FOVEATION_LEVEL_HIGH_FB = 3,
            XR_FOVEATION_LEVEL_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrFoveationDynamicFB
        {
            XR_FOVEATION_DYNAMIC_DISABLED_FB = 0,
            XR_FOVEATION_DYNAMIC_LEVEL_ENABLED_FB = 1,
            XR_FOVEATION_DYNAMIC_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrWindingOrderFB
        {
            XR_WINDING_ORDER_UNKNOWN_FB = 0,
            XR_WINDING_ORDER_CW_FB = 1,
            XR_WINDING_ORDER_CCW_FB = 2,
            XR_WINDING_ORDER_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrPassthroughLayerPurposeFB
        {
            XR_PASSTHROUGH_LAYER_PURPOSE_RECONSTRUCTION_FB = 0,
            XR_PASSTHROUGH_LAYER_PURPOSE_PROJECTED_FB = 1,
            XR_PASSTHROUGH_LAYER_PURPOSE_TRACKED_KEYBOARD_HANDS_FB = 1000203001,
            XR_PASSTHROUGH_LAYER_PURPOSE_TRACKED_KEYBOARD_MASKED_HANDS_FB = 1000203002,
            XR_PASSTHROUGH_LAYER_PURPOSE_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrHandForearmJointULTRALEAP
        {
            XR_HAND_FOREARM_JOINT_PALM_ULTRALEAP = 0,
            XR_HAND_FOREARM_JOINT_WRIST_ULTRALEAP = 1,
            XR_HAND_FOREARM_JOINT_THUMB_METACARPAL_ULTRALEAP = 2,
            XR_HAND_FOREARM_JOINT_THUMB_PROXIMAL_ULTRALEAP = 3,
            XR_HAND_FOREARM_JOINT_THUMB_DISTAL_ULTRALEAP = 4,
            XR_HAND_FOREARM_JOINT_THUMB_TIP_ULTRALEAP = 5,
            XR_HAND_FOREARM_JOINT_INDEX_METACARPAL_ULTRALEAP = 6,
            XR_HAND_FOREARM_JOINT_INDEX_PROXIMAL_ULTRALEAP = 7,
            XR_HAND_FOREARM_JOINT_INDEX_INTERMEDIATE_ULTRALEAP = 8,
            XR_HAND_FOREARM_JOINT_INDEX_DISTAL_ULTRALEAP = 9,
            XR_HAND_FOREARM_JOINT_INDEX_TIP_ULTRALEAP = 10,
            XR_HAND_FOREARM_JOINT_MIDDLE_METACARPAL_ULTRALEAP = 11,
            XR_HAND_FOREARM_JOINT_MIDDLE_PROXIMAL_ULTRALEAP = 12,
            XR_HAND_FOREARM_JOINT_MIDDLE_INTERMEDIATE_ULTRALEAP = 13,
            XR_HAND_FOREARM_JOINT_MIDDLE_DISTAL_ULTRALEAP = 14,
            XR_HAND_FOREARM_JOINT_MIDDLE_TIP_ULTRALEAP = 15,
            XR_HAND_FOREARM_JOINT_RING_METACARPAL_ULTRALEAP = 16,
            XR_HAND_FOREARM_JOINT_RING_PROXIMAL_ULTRALEAP = 17,
            XR_HAND_FOREARM_JOINT_RING_INTERMEDIATE_ULTRALEAP = 18,
            XR_HAND_FOREARM_JOINT_RING_DISTAL_ULTRALEAP = 19,
            XR_HAND_FOREARM_JOINT_RING_TIP_ULTRALEAP = 20,
            XR_HAND_FOREARM_JOINT_LITTLE_METACARPAL_ULTRALEAP = 21,
            XR_HAND_FOREARM_JOINT_LITTLE_PROXIMAL_ULTRALEAP = 22,
            XR_HAND_FOREARM_JOINT_LITTLE_INTERMEDIATE_ULTRALEAP = 23,
            XR_HAND_FOREARM_JOINT_LITTLE_DISTAL_ULTRALEAP = 24,
            XR_HAND_FOREARM_JOINT_LITTLE_TIP_ULTRALEAP = 25,
            XR_HAND_FOREARM_JOINT_ELBOW_ULTRALEAP = 26,
            XR_HAND_FOREARM_JOINT_MAX_ENUM_ULTRALEAP = 0x7FFFFFFF,
            
        }
    
        enum XrSpaceQueryActionFB
        {
            XR_SPACE_QUERY_ACTION_LOAD_FB = 0,
            XR_SPACE_QUERY_ACTION_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrSpaceStorageLocationFB
        {
            XR_SPACE_STORAGE_LOCATION_INVALID_FB = 0,
            XR_SPACE_STORAGE_LOCATION_LOCAL_FB = 1,
            XR_SPACE_STORAGE_LOCATION_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrSpacePersistenceModeFB
        {
            XR_SPACE_PERSISTENCE_MODE_INVALID_FB = 0,
            XR_SPACE_PERSISTENCE_MODE_INDEFINITE_FB = 1,
            XR_SPACE_PERSISTENCE_MODE_MAX_ENUM_FB = 0x7FFFFFFF,
            
        }
    
        enum XrPerformanceMetricsCounterUnitMETA
        {
            XR_PERFORMANCE_METRICS_COUNTER_UNIT_GENERIC_META = 0,
            XR_PERFORMANCE_METRICS_COUNTER_UNIT_PERCENTAGE_META = 1,
            XR_PERFORMANCE_METRICS_COUNTER_UNIT_MILLISECONDS_META = 2,
            XR_PERFORMANCE_METRICS_COUNTER_UNIT_BYTES_META = 3,
            XR_PERFORMANCE_METRICS_COUNTER_UNIT_HERTZ_META = 4,
            XR_PERFORMANCE_METRICS_COUNTER_UNIT_MAX_ENUM_META = 0x7FFFFFFF,
            
        }
    
        enum XrPassthroughFormHTC
        {
            XR_PASSTHROUGH_FORM_PLANAR_HTC = 0,
            XR_PASSTHROUGH_FORM_PROJECTED_HTC = 1,
            XR_PASSTHROUGH_FORM_MAX_ENUM_HTC = 0x7FFFFFFF,
            
        }
    
        enum XrFoveationModeHTC
        {
            XR_FOVEATION_MODE_DISABLE_HTC = 0,
            XR_FOVEATION_MODE_FIXED_HTC = 1,
            XR_FOVEATION_MODE_DYNAMIC_HTC = 2,
            XR_FOVEATION_MODE_CUSTOM_HTC = 3,
            XR_FOVEATION_MODE_MAX_ENUM_HTC = 0x7FFFFFFF,
            
        }
    
        enum XrFoveationLevelHTC
        {
            XR_FOVEATION_LEVEL_NONE_HTC = 0,
            XR_FOVEATION_LEVEL_LOW_HTC = 1,
            XR_FOVEATION_LEVEL_MEDIUM_HTC = 2,
            XR_FOVEATION_LEVEL_HIGH_HTC = 3,
            XR_FOVEATION_LEVEL_MAX_ENUM_HTC = 0x7FFFFFFF,
            
        }
    
}